name: Windows Build Action 😎

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build my project ✨
    runs-on: [self-hosted]
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v3.2.6
        with:
          path: 3dSinUnityProject/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          customImage: 'unityci/editor:ubuntu-2020.3.21f1-windows-mono-1.1.2'
          projectPath: 3dSinUnityProject
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Build
          path: build
